### ISSUE TITLE
💡 Add GraphQL guide

### ISSUE THREAD

**Issue by TomWFox** [parse-community/parse-community.github.io#29]
We now have a GraphQL guide in our open source Docs which should be referenced here.

@davimacedo here if you want to do this before I get to it.

**Comment by dplewis** [comment]
Someone deleted the gh-pages branch. Can you look into it?

**Comment by TomWFox** [comment]
@dplewis My bad, fixed now, sorry for the delay.

**Comment by davimacedo** [comment]
done
https://github.com/parse-community/parse-community.github.io/pull/31
