### ISSUE TITLE
Community Site Down

### ISSUE THREAD

**Issue by Moumouls** [parse-community/parse-community.github.io#35]
Hi everyone,

@davimacedo , @TomWFox , @acinader , @dplewis ,  @natanrolnik 
It seems that the community site is down from now 2-3 weeks, does any body have an access or know the origin of the failure ? 😄 

Best regards !

**Comment by Moumouls** [comment]
https://community.parseplatform.org

**Comment by TomWFox** [comment]
@Moumouls I've shared what I know on the parse-server #6417 issue, the forum is not related to this repo so I think we should keep the discussion on that existing issue
