### ISSUE TITLE
buttons are hidden behind skyline image

### ISSUE THREAD

**Issue by yhdesai** [parse-community/parse-community.github.io#8]

**Comment by yhdesai** [comment]
Reference Image for the same:  
http://imgur.com/UpBgkJwl.png

**Comment by flovilmart** [comment]
Feel free to provide a fix, otherwise it will be revisited in the future.

**Comment by TomWFox** [comment]
The resizing of the header is still not perfect (I noticed on some screen heights it's still a bit weird) but I mostly fixed these issues in #12
